name: Part Three (Confirming Test Is Flaky With Cloud Run)

on:
  workflow_dispatch:

jobs:
  run_commands:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: raphw/byte-buddy
        ref: master

    - name: Build project (clean install without tests)
      run: mvn clean install -DskipTests -pl byte-buddy-dep -am

    - name: Run without the NonDex tool(Regular Run)
      run: mvn -pl byte-buddy-dep test -Dtest=net.bytebuddy.description.method.MethodDescriptionLatentTest#testToString

    - name: Run with the NonDex tool
      run: mvn -pl byte-buddy-dep edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=net.bytebuddy.description.method.MethodDescriptionLatentTest#testToString

