name: Execute Commands

on:
  workflow_dispatch:

jobs:
  run_commands:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Change directory to home
      run: cd ~

    - name: Clone repository
      run: git clone https://github.com/apache/servicecomb-java-chassis

    - name: Change directory to servicecomb-java-chassis
      run: cd servicecomb-java-chassis

    - name: Checkout specific commit
      run: git checkout eec5b5cb85b3b9c11628f3b9d2b0a4456e177495

    - name: Build project (clean install without tests)
      run: mvn clean install -DskipTests -pl swagger/swagger-generator -am

    - name: Run specific test
      run: mvn -pl swagger/swagger-generator test -Dtest=org.apache.servicecomb.swagger.generator.core.TestSwaggerUtils#should_not_lost_ApiParam_description_when_wrap_parameter_to_body

    - name: Run non-deterministic test
      run: mvn -pl swagger/swagger-generator edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.servicecomb.swagger.generator.core.TestSwaggerUtils#should_not_lost_ApiParam_description_when_wrap_parameter_to_body
